
CREATE DATABASE spotify;
USE spotify;

CREATE TABLE Songs(title VARCHAR(255) PRIMARY KEY NOT NULL, artist VARCHAR(255) NOT NULL, duration VARCHAR(255), genre CHAR(50) NOT NULL, explicit CHAR(1) NOT NULL, url CHAR(50) NOT NULL);

CREATE TABLE Artist(firstName VARCHAR(255) PRIMARY KEY NOT NULL, lastName VARCHAR(255) NOT NULL, dateOfBirth DATE);

CREATE TABLE Genre(id VARCHAR(255) PRIMARY KEY);

CREATE TABLE Users(email VARCHAR(50) PRIMARY KEY NOT NULL UNIQUE, firstName VARCHAR(255) NOT NULL, lastName VARCHAR(255) NOT NULL, password VARCHAR(25) UNIQUE NOT NULL, favorites VARCHAR(255), playlist VARCHAR(255));

CREATE TABLE Playist(id integer PRIMARY KEY NOT NULL AUTO_INCREMENT, sequence INT(10), rating INT(10), FOREIGN KEY (genre) REFERENCES users);